export const routes = {
  home: '/',
  list: 'list',
  companies: 'companies',
  companyDetails: 'companies/:id',
  cards: 'cards',
  cardDetails: 'cards/:id',
  customers: 'customers',
  customerDetails: 'customers/:id',
  invoices: 'invoices',
  invoiceDetails: 'invoices/:id',
  adding: 'adding',
  editing: 'edit/:id/:type',
  login: 'login'
}

export const functionNames = {
  getCompanies: 'getCompanies',
  getCompany: 'getCompany',
  addCompany: 'addCompany',
  updateCompany: 'updateCompany',
  deleteCompany: 'deleteCompany',
  getCustomers: 'getCustomers',
  getCustomer: 'getCustomer',
  addCustomer: 'addCustomer',
  updateCustomer: 'updateCustomer',
  deleteCustomer: 'deleteCustomer',
  getCards: 'getCards',
  getUnOccupiedCards: 'getUnOccupiedCards',
  getCard: 'getCard',
  getCardsFromCompanyId: 'getCardsFromCompanyId',
  getCardsFromCustomerId: 'getCardsFromCustomerId',
  addCard: 'addCard',
  updateCard: 'updateCard',
  deleteCard: 'deleteCard',
  getList: 'getList',
  getInvoices: 'getInvoices',
  addInvoice: 'addInvoice',
  updateInvoice: 'updateInvoice',
  deleteInvoice: 'deleteInvoice',
  getOffers: 'getOffers',
  getOffer: 'getOffer',
  addOffer: 'addOffer',
  updateOffer: 'updateOffer',
  deleteOffer: 'deleteOffer'
}
